# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  GLFW_config = debug_x64
  JoltPhysics_config = debug_x64
  ImGui_config = debug_x64
  Engine_config = debug_x64
  Shaders_config = debug_x64

else ifeq ($(config),release_x64)
  GLFW_config = release_x64
  JoltPhysics_config = release_x64
  ImGui_config = release_x64
  Engine_config = release_x64
  Shaders_config = release_x64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW JoltPhysics ImGui Engine Shaders

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Intermediate/Projects -f GLFW.make config=$(GLFW_config)
endif

JoltPhysics:
ifneq (,$(JoltPhysics_config))
	@echo "==== Building JoltPhysics ($(JoltPhysics_config)) ===="
	@${MAKE} --no-print-directory -C Intermediate/Projects -f JoltPhysics.make config=$(JoltPhysics_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Intermediate/Projects -f ImGui.make config=$(ImGui_config)
endif

Engine: GLFW JoltPhysics ImGui Shaders
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C Intermediate/Projects -f Engine.make config=$(Engine_config)
endif

Shaders:
ifneq (,$(Shaders_config))
	@echo "==== Building Shaders ($(Shaders_config)) ===="
	@${MAKE} --no-print-directory -C Intermediate/Projects -f Shaders.make config=$(Shaders_config)
endif

clean:
	@${MAKE} --no-print-directory -C Intermediate/Projects -f GLFW.make clean
	@${MAKE} --no-print-directory -C Intermediate/Projects -f JoltPhysics.make clean
	@${MAKE} --no-print-directory -C Intermediate/Projects -f ImGui.make clean
	@${MAKE} --no-print-directory -C Intermediate/Projects -f Engine.make clean
	@${MAKE} --no-print-directory -C Intermediate/Projects -f Shaders.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   JoltPhysics"
	@echo "   ImGui"
	@echo "   Engine"
	@echo "   Shaders"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"