#include "Runtime/UI/EditorLayout.hpp"
#include "Runtime/UI/SwitchLanguage.hpp"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>

namespace layout = engine::editor_layout;

namespace {
    constexpr const char* kCoreWindows[] = {
        layout::kSceneHierarchy, layout::kEntityInspector, layout::kSceneViewport,
        layout::kAssets, layout::kConsole
    };
    constexpr const char* kOptionalWindows[] = {
        layout::kRenderSettings, layout::kLighting, layout::kCamera,
        layout::kAudio, layout::kDiagnostics, layout::kParticles, layout::kRuntimeUiDebug
    };

    void Require(bool condition, const std::string& message) {
        if (!condition) {
            std::fprintf(stderr, "FAIL: %s\n", message.c_str());
            std::exit(1);
        }
    }

    ImGuiID RootId() { return ImHashStr(layout::kDockspaceName); }

    std::string PanelTitle(const char* canonicalTitle) {
        const std::string title(canonicalTitle);
        const size_t stableId = title.find("###");
        Require(stableId != std::string::npos, "panel has a stable ID");
        // Use the same translation source and title construction as EngineUi.
        return std::string(engine::Translator::SL(title.substr(0, stableId).c_str())) + title.substr(stableId);
    }

    struct HeadlessContext {
        ImGuiContext* context;

        HeadlessContext(int width, int height, const std::string& ini = {}) {
            context = ImGui::CreateContext();
            ImGuiIO& io = ImGui::GetIO();
            io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;
            io.IniFilename = nullptr;
            io.LogFilename = nullptr;
            io.DisplaySize = ImVec2(static_cast<float>(width), static_cast<float>(height));
            io.DeltaTime = 1.0f / 60.0f;
            // Build the actual atlas without a graphics backend. Draw data is
            // generated by ImGui::Render(), but no GPU or native window is used.
            unsigned char* pixels;
            int atlasWidth, atlasHeight;
            io.Fonts->GetTexDataAsRGBA32(&pixels, &atlasWidth, &atlasHeight);
            Require(pixels && atlasWidth > 0 && atlasHeight > 0, "real font atlas built");
            if (!ini.empty()) ImGui::LoadIniSettingsFromMemory(ini.data(), ini.size());
        }

        ~HeadlessContext() { ImGui::DestroyContext(context); }

        void Begin() {
            ImGui::NewFrame();
            if (ImGui::BeginMainMenuBar()) {
                ImGui::TextUnformatted("File   View   Tools");
                ImGui::EndMainMenuBar();
            }
        }

        void Windows(bool optional = true) {
            const auto draw = [](const char* name) {
                ImGui::Begin(PanelTitle(name).c_str());
                ImGui::TextUnformatted("Editor panel");
                ImGui::End();
            };
            // Match production submission order: early tool/console windows
            // must not steal the default active inspector/assets tabs.
            draw(layout::kRenderSettings);
            if (optional) draw(layout::kParticles);
            draw(layout::kConsole);
            draw(layout::kAssets);
            draw(layout::kSceneHierarchy);
            draw(layout::kEntityInspector);
            draw(layout::kSceneViewport);
            if (optional) {
                for (const char* name : kOptionalWindows) {
                    if (name != layout::kRenderSettings && name != layout::kParticles) draw(name);
                }
            }
        }

        void Frame(bool reset = false, bool optional = true) {
            Begin();
            layout::DrawDockspace(reset);
            Windows(optional);
            ImGui::Render();
        }

        void Settle(bool optional = true) {
            for (int frame = 0; frame < 6; ++frame) Frame(false, optional);
        }

        std::string Save() {
            size_t length = 0;
            const char* data = ImGui::SaveIniSettingsToMemory(&length);
            return std::string(data, length);
        }
    };

    ImGuiWindow& Window(const char* title) {
        ImGuiWindow* window = ImGui::FindWindowByName(title);
        Require(window != nullptr, std::string("real window exists: ") + title);
        Require(window->DockNode != nullptr, std::string("window is docked: ") + title);
        Require(ImGui::DockNodeGetRootNode(window->DockNode)->ID == RootId(),
            std::string("window uses the versioned root: ") + title);
        return *window;
    }

    void Near(float actual, float expected, float tolerance, const char* label) {
        Require(std::abs(actual - expected) <= tolerance,
            std::string(label) + " actual=" + std::to_string(actual) + " expected=" + std::to_string(expected));
    }

    void CheckDefault(bool optional = true, bool checkActiveTabs = true) {
        auto& hierarchy = Window(layout::kSceneHierarchy);
        auto& inspector = Window(layout::kEntityInspector);
        auto& scene = Window(layout::kSceneViewport);
        auto& assets = Window(layout::kAssets);
        auto& console = Window(layout::kConsole);
        const auto* viewport = ImGui::GetMainViewport();
        Require(ImGui::DockBuilderGetCentralNode(RootId()) == scene.DockNode,
            "scene viewport owns central node");
        Require(hierarchy.DockId != scene.DockId && inspector.DockId != scene.DockId &&
            assets.DockId != scene.DockId, "main editor regions are separate");
        Require(assets.DockId == console.DockId, "assets and console share bottom tabs");
        if (checkActiveTabs) {
            Require(inspector.DockNode->SelectedTabId == inspector.TabId,
                "inspector is the default active right tab regardless of submission order");
            Require(assets.DockNode->SelectedTabId == assets.TabId,
                "assets is the default active bottom tab regardless of submission order");
        }
        Require(hierarchy.DockNode->Pos.x < scene.DockNode->Pos.x &&
            scene.DockNode->Pos.x < inspector.DockNode->Pos.x, "hierarchy / scene / inspector order");
        Require(assets.DockNode->Pos.y > scene.DockNode->Pos.y, "assets are below scene");
        Near(hierarchy.DockNode->Size.x / viewport->WorkSize.x, 0.18f, 0.015f, "left width ratio");
        Near(inspector.DockNode->Size.x / viewport->WorkSize.x, 0.25f, 0.015f, "right width ratio");
        Near(assets.DockNode->Size.y / viewport->WorkSize.y, 0.22f, 0.015f, "bottom height ratio");
        const float contentArea = scene.InnerRect.GetWidth() * scene.InnerRect.GetHeight();
        const float screenArea = viewport->Size.x * viewport->Size.y;
        Require(contentArea / screenArea >= 0.30f, "scene content retains at least 30 percent of the screen");
        for (const char* title : kOptionalWindows) {
            if (optional) {
                Require(Window(title).DockId == inspector.DockId, std::string("right tab: ") + title);
            }
            else if (title != layout::kRenderSettings) {
                const auto* settings = ImGui::FindWindowSettingsByID(ImHashStr(title));
                Require(settings && settings->DockId == inspector.DockId,
                    std::string("closed optional panel retains its right-tab destination: ") + title);
            }
        }
        std::printf("PASS default %.0fx%.0f: scene content %.1f%%, left %.1f%%, right %.1f%%, bottom %.1f%%\n",
            viewport->Size.x, viewport->Size.y, contentArea / screenArea * 100.0f,
            hierarchy.DockNode->Size.x / viewport->WorkSize.x * 100.0f,
            inspector.DockNode->Size.x / viewport->WorkSize.x * 100.0f,
            assets.DockNode->Size.y / viewport->WorkSize.y * 100.0f);
    }

    void TestDefault(int width, int height) {
        HeadlessContext fixture(width, height);
        fixture.Settle();
        CheckDefault();
    }

    void TestClosedOptionalPanels() {
        HeadlessContext fixture(1280, 720);
        fixture.Settle(false);
        CheckDefault(false);
        fixture.Settle(true);
        CheckDefault(true, false); // Opening a tool may select it, as requested by the user.
        std::puts("PASS initially closed optional panels open in the reserved inspector tabs");
    }

    void BuildCustomLayout() {
        ImGui::DockBuilderRemoveNodeChildNodes(RootId());
        ImGuiID center = RootId();
        const ImGuiID left = ImGui::DockBuilderSplitNode(center, ImGuiDir_Left, 0.34f, nullptr, &center);
        const ImGuiID bottom = ImGui::DockBuilderSplitNode(center, ImGuiDir_Down, 0.38f, nullptr, &center);
        ImGui::DockBuilderDockWindow(layout::kSceneHierarchy, left);
        ImGui::DockBuilderDockWindow(layout::kEntityInspector, left);
        for (const char* title : kOptionalWindows) ImGui::DockBuilderDockWindow(title, left);
        ImGui::DockBuilderDockWindow(layout::kSceneViewport, center);
        ImGui::DockBuilderDockWindow(layout::kConsole, center);
        ImGui::DockBuilderDockWindow(layout::kAssets, bottom);
        ImGui::DockBuilderFinish(RootId());
    }

    void CheckCustom() {
        const auto& hierarchy = Window(layout::kSceneHierarchy);
        Require(Window(layout::kEntityInspector).DockId == hierarchy.DockId, "custom inspector stays on the left");
        Require(Window(layout::kConsole).DockId == Window(layout::kSceneViewport).DockId,
            "custom console stays tabbed with scene");
        Require(Window(layout::kAssets).DockId != Window(layout::kConsole).DockId,
            "custom assets and console remain separate");
        Near(hierarchy.DockNode->Size.x / ImGui::GetMainViewport()->WorkSize.x, 0.34f, 0.015f,
            "custom left width survives");
    }

    void TestPersistenceAndReset() {
        std::string saved;
        ImGuiID savedSceneDock = 0;
        {
            HeadlessContext fixture(1920, 1080);
            fixture.Settle();
            fixture.Begin();
            BuildCustomLayout();
            layout::DrawDockspace();
            fixture.Windows();
            ImGui::Render();
            fixture.Settle();
            CheckCustom();
            ImGui::FocusWindow(&Window(layout::kLighting));
            fixture.Settle();
            Require(Window(layout::kLighting).DockNode->SelectedTabId == Window(layout::kLighting).TabId,
                "user-selected lighting tab is not replaced by the default inspector");
            savedSceneDock = Window(layout::kSceneViewport).DockId;
            saved = fixture.Save();
        }
        {
            HeadlessContext fixture(1920, 1080, saved);
            fixture.Settle();
            CheckCustom();
            Require(Window(layout::kSceneViewport).DockId == savedSceneDock,
                "new context restores saved node IDs without rebuilding");
            fixture.Frame(true);
            fixture.Settle();
            CheckDefault();
            std::puts("PASS custom layout survives frames and ini round-trip; reset restores defaults");
        }
    }

    void TestOldDockspaceMigration() {
        std::string oldIni;
        ImGuiID oldRoot = 0;
        {
            HeadlessContext fixture(1280, 720);
            fixture.Begin();
            oldRoot = ImGui::DockSpaceOverViewport(0, ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode);
            fixture.Windows();
            ImGui::Render();
            fixture.Begin();
            for (const char* title : kCoreWindows) ImGui::DockBuilderDockWindow(title, oldRoot);
            for (const char* title : kOptionalWindows) ImGui::DockBuilderDockWindow(title, oldRoot);
            ImGui::DockBuilderFinish(oldRoot);
            ImGui::DockSpaceOverViewport(0, ImGui::GetMainViewport(), ImGuiDockNodeFlags_PassthruCentralNode);
            fixture.Windows();
            ImGui::Render();
            oldIni = fixture.Save();
        }
        {
            HeadlessContext fixture(1280, 720, oldIni);
            Require(oldRoot != RootId(), "versioned root differs from DockSpaceOverViewport default ID");
            fixture.Settle();
            CheckDefault();
            std::puts("PASS legacy default-dockspace ini cannot override the new initial layout");
        }
    }

    void TestLanguageSwitch() {
        std::string saved;
        ImGuiID customSceneDock = 0;
        {
            HeadlessContext fixture(1280, 720);
            fixture.Settle();
            const auto* originalHierarchy = &Window(layout::kSceneHierarchy);
            const ImGuiID originalDock = originalHierarchy->DockId;
            engine::Translator::SetLanguage(engine::Language::Chinese);
            Require(std::string(engine::Translator::SL("Scene Hierarchy")) != "Scene Hierarchy",
                "test exercises actual Chinese translation rather than untranslated labels");
            fixture.Settle();
            Require(&Window(layout::kSceneHierarchy) == originalHierarchy &&
                Window(layout::kSceneHierarchy).DockId == originalDock,
                "language switch retains the window object and docking ID");
            Require(std::string(Window(layout::kSceneHierarchy).Name) == PanelTitle(layout::kSceneHierarchy),
                "displayed window title uses the real translated label");
            CheckDefault();
            fixture.Begin();
            BuildCustomLayout();
            layout::DrawDockspace();
            fixture.Windows();
            ImGui::Render();
            fixture.Settle();
            CheckCustom();
            customSceneDock = Window(layout::kSceneViewport).DockId;
            saved = fixture.Save();
        }
        {
            engine::Translator::SetLanguage(engine::Language::English);
            HeadlessContext fixture(1280, 720, saved);
            fixture.Settle();
            CheckCustom();
            Require(Window(layout::kSceneViewport).DockId == customSceneDock,
                "Chinese-saved layout survives reload with English titles");
        }
        std::puts("PASS actual Chinese/English panel titles retain stable IDs and saved docking");
    }
}

int main() {
    TestDefault(1280, 720);
    TestDefault(1920, 1080);
    TestClosedOptionalPanels();
    TestPersistenceAndReset();
    TestOldDockspaceMigration();
    TestLanguageSwitch();
    std::puts("PASS all editor layout tests (real ImGui docking; no window or graphics backend)");
}
