#pragma execution_character_set("utf-8")
#include "SwitchLanguage.hpp"

namespace engine {

    Language Translator::CurrentLanguage = Language::English;

    std::unordered_map<std::string, std::string> Translator::ChineseDict = {
        {"Scene Hierarchy", "场景层级"},
        {"Entity Inspector", "实体属性"},
        {"Assets", "资源浏览器"},
        {"Console", "日志控制台"},
        {"Render Settings", "渲染设置"},
        {"Lighting", "灯光"},
        {"Camera", "相机"},
        {"Particles", "粒子"},
        {"Audio", "音频"},
        {"Diagnostics", "诊断"},
        {"File", "文件"},
        {"Window", "窗口"},
        {"View", "视图"},
        {"Help", "帮助"},
        {"Engine UI", "引擎编辑器"},
        {"Neutral Viewport Background", "视口浅灰背景"},
        {"Viewport Grid", "视口参考网格"},
        {"Available in default render mode", "仅在默认渲染模式下可用"},
        {"Game UI Tools", "游戏 UI 工具"},
        {"Game UI Editor", "游戏 UI 编辑器"},
        {"Runtime UI Debug", "运行时 UI 诊断"},
        {"Reset Editor Layout", "恢复编辑器布局"},
        {"Language", "界面语言"},
        {"Save Scene Snapshot", "保存场景快照"},
        {"Load Scene Snapshot", "载入场景快照"},
        {"Exit Engine", "退出引擎"},
        {"Exposure", "曝光"},
        {"Bloom Strength", "泛光强度"},
        {"Enable Bloom", "启用泛光"},
        {"Engine Control Panel", "游戏引擎调试面板"},
        {"[ Performance ]", "[ 性能与渲染 ]"},
        {"FPS: %.3f ms", "帧耗时: %.3f ms"},
        {"View Mode", "渲染模式"},
        {"Default", "默认"},
        {"Mipmaps", "纹理 Mip 层级"},
        {"Depth", "深度"},
        {"Derivatives", "深度变化率"},
        {"Overdraw", "过度绘制"},
        {"Overshading", "重复着色"},
        {"Normals", "法线"},
        {"Wireframe", "线框"},
        {"Shadow", "阴影"},
        {"Wireframe is not supported by this graphics device.", "当前显卡不支持线框光栅化。"},
        {"SSAO buffer: white is unoccluded, darker areas are occluded. Computed even when SSAO is disabled in Default view.", "SSAO 缓冲：白色表示无遮挡，越暗遮蔽越强。即使默认视图关闭 SSAO，此视图也会单独计算。"},
        {"SSR buffer: reflection color weighted by hit confidence. Black means no valid reflection; rough or off-screen surfaces may have no hit. Computed even when SSR is disabled in Default view.", "SSR 缓冲：按命中可信度显示反射颜色。黑色表示无有效反射；粗糙表面或屏幕外目标可能无法命中。即使默认视图关闭 SSR，此视图也会单独计算。"},
        {"World-space shading normals, including normal maps: X/Y/Z map to R/G/B. Empty pixels are black.", "包含法线贴图的世界空间着色法线：X/Y/Z 对应 R/G/B，空像素为黑色。"},
        {"Triangle edges for static and animated meshes. Surfaces are unfilled, so edges behind them may also be visible.", "显示静态与骨骼模型的三角形边。表面不填充，因此也可能看到背后的边。"},
        {"Base-color texture multiplied by the material color, without lighting, AO, shadows or tone mapping.", "基础颜色贴图乘以材质颜色，不叠加光照、AO、阴影或色调映射。"},
        {"Directional-light cascaded shadow visibility: white is lit, black is shadowed. Includes cascade blending; spotlight shadows are not shown.", "方向光级联阴影可见度：白色受光，黑色被遮挡，包含级联过渡。不包含聚光灯阴影。"},
        {"Buffer views use opaque and alpha-cutout geometry, including animated meshes. Transparent blending and display post-processing are omitted.", "缓冲视图包含不透明和透明裁切几何（含骨骼模型），不叠加半透明混合与显示后处理。"},
        {"Lit scene with the current rendering settings.", "按当前渲染设置显示场景。"},
        {"Texture mip level: 0 red, 1 green, 2 blue, 3 yellow, 4 cyan, 5 magenta; colors repeat every 6 levels.", "纹理 Mip 层级：0 红、1 绿、2 蓝、3 黄、4 青、5 品红，每 6 层循环。"},
        {"Camera distance on a logarithmic scale: near is black, far is white; empty background is black.", "以对数比例显示相机距离：近黑远白，空背景为黑色。"},
        {"Relative depth change per pixel: horizontal red, vertical green; surfaces parallel to the camera plane are dark.", "逐像素的相对深度变化：水平变化为红色，垂直变化为绿色，无变化区域为黑色。"},
        {"Selection wireframes require Default view.", "选择辅助线仅在默认视图下显示。"},
        {"Covered layers without depth rejection: brighter means more overlap, white at 20 layers.", "不剔除被遮挡片元的覆盖层数：越亮表示重叠越多，20 层达到白色。"},
        {"Layers passing depth in draw order: brighter means more shading, white at 20 layers. This is an estimate, not GPU timing.", "按绘制顺序累计通过深度测试的层数：越亮表示重复着色越多，20 层达到白色。这是估算，不是 GPU 耗时。"},
        {"Diagnostic views display their rendering data directly. Return to Default to adjust scene effects.", "诊断视图直接显示对应的渲染数据，切回默认模式后可调整场景效果。"},
        {"Debug views include static and animated meshes; sky, particles, portal views and post-processing are omitted.", "调试视图包含静态和骨骼模型，跳过天空、粒子、传送门画面与后处理。"},
        {"Particle System", "启用粒子系统"},
        {"Enable Mosaic Post-Process", "马赛克后处理"},
        {"[ generator ]", "[ 物理实体生成器 ]"},
        {"Height", "生成高度 (Y轴)"},
        {"select", "选择模型"},
        {"Spawn!!!!", "从天而降!"},
        {"Switch Language", "切换语言"},
        //粒子系统编辑器
		//particle editor
        {"[ Particle Editor ]", "[ 粒子系统实时编辑器 ]"},
        {"Select Particle", "选择粒子组"},
        {"Emitter Settings", "发射器设置"},
        {"Physics & Movement", "物理与运动"},
        {"Appearance & Color", "外观与颜色"},
        {"Life Cycle", "生命周期"},
        {"Emitter Shape", "发射器形态"},
        {"Emitter Pos", "发射器位置 (XYZ)"},
        {"Cone Spread", "锥形散射角度"},
        {"Sphere Radius", "球形发射半径"},
        {"Box Area", "盒形发射范围 (XYZ)"},
        {"Show Debug Wireframe", "显示调试线框"},
        {"Gravity", "重力影响 (XYZ)"},
        {"Speed Min", "最小初速度"},
        {"Speed Max", "最大初速度"},
        {"Rotation Min", "最小初始旋转 (度)"},
        {"Rotation Max", "最大初始旋转 (度)"},
        {"Size Min", "最小尺寸"},
        {"Size Max", "最大尺寸"},
        {"Start Size Scale", "出生时尺寸缩放"},
        {"End Size Scale", "死亡时尺寸缩放"},
        {"Start Color", "出生颜色 (RGBA)"},
        {"End Color", "消散颜色 (RGBA)"},
        {"Atlas Cols", "贴图列数 (Cols)"},
        {"Atlas Rows", "贴图行数 (Rows)"},
        {"Animate Atlas", "播放序列帧动画"},
        {"Life Min", "最短寿命 (秒)"},
        {"Life Max", "最长寿命 (秒)"},
        {"Add Group", "新增粒子组"},
        {"Delete Group", "删除当前组"},
        {"Visible", "显示 / 隐藏"},
        {"Name", "重命名 (Name)"},
        {"Use Texture", "使用贴图"},
        {"Select Texture", "选择贴图文件"},
        {"Max Particles", "最大粒子数量"},
        {"Apply Changes", "应用更改 (重置)"},
		//主菜单
        {"MAIN MENU", "主菜单"},
        {"Start Game", "开始游戏"},
        {"Exit Game", "退出游戏"},
        {"Setting", "设置"},
    };

} // namespace engine
